# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_analysis.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'video_analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14video_analysis.proto\x12\rvideoanalysis\"\x8b\x01\n\x0eProcessRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08\x63hunk_id\x18\x02 \x01(\x03\x12\x12\n\nvideo_path\x18\x03 \x01(\t\x12\x15\n\ranalysis_mode\x18\x04 \x01(\t\x12\x13\n\x0bwindow_size\x18\x05 \x01(\x05\x12\x13\n\x0bwindow_step\x18\x06 \x01(\x05\"6\n\x0fProcessResponse\x12\x14\n\x0cwindow_paths\x18\x01 \x03(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x9b\x01\n\x0f\x41nalysisRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x14\n\x0cwindow_index\x18\x02 \x01(\x05\x12\x11\n\tvideo_url\x18\x03 \x01(\t\x12\x10\n\x08\x61i_model\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x05 \x01(\t\x12\x14\n\x0cstart_offset\x18\x06 \x01(\x05\x12\x12\n\nend_offset\x18\x07 \x01(\x05\"n\n\x10\x41nalysisResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x14\n\x0cwindow_index\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x10\n\x08is_final\x18\x04 \x01(\x08\x12\r\n\x05\x65rror\x18\x05 \x01(\t2\xb8\x01\n\x14VideoAnalysisService\x12M\n\x0cProcessVideo\x12\x1d.videoanalysis.ProcessRequest\x1a\x1e.videoanalysis.ProcessResponse\x12Q\n\x0c\x41nalyzeVideo\x12\x1e.videoanalysis.AnalysisRequest\x1a\x1f.videoanalysis.AnalysisResponse0\x01\x42&\n\x0e\x63om.skiuo.grpcB\x12VideoAnalysisProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.skiuo.grpcB\022VideoAnalysisProtoP\001'
  _globals['_PROCESSREQUEST']._serialized_start=40
  _globals['_PROCESSREQUEST']._serialized_end=179
  _globals['_PROCESSRESPONSE']._serialized_start=181
  _globals['_PROCESSRESPONSE']._serialized_end=235
  _globals['_ANALYSISREQUEST']._serialized_start=238
  _globals['_ANALYSISREQUEST']._serialized_end=393
  _globals['_ANALYSISRESPONSE']._serialized_start=395
  _globals['_ANALYSISRESPONSE']._serialized_end=505
  _globals['_VIDEOANALYSISSERVICE']._serialized_start=508
  _globals['_VIDEOANALYSISSERVICE']._serialized_end=692
# @@protoc_insertion_point(module_scope)
